GET http://localhost:4000

### Add user 
POST http://localhost:4000/api/users
content-type: application/json

{
  "name": "Gollum"
}

### Add post
POST http://localhost:4000/api/users/1/posts
content-type: application/json

{
  "text": "You know nothing John Snow",
  "user_id": 100
}

### Get All users 
GET http://localhost:4000/api/users

### Get user by ID 
GET http://localhost:4000/api/users/2

### Get posts by user ID 
GET http://localhost:4000/api/users/1/posts

### Delete user 
DELETE http://localhost:4000/api/users/10

### Update user
PUT http://localhost:4000/api/users/1
content-type: application/json

{
  "name": "Frodo"
}